import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { HomePath, ticketsPath } from "@/paths";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The road to next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="supports-backdrop-blur:bg-background/60
                        fixed left-0 right-0 top-0 z-20
                        border-b background/95 backdrop-blur
                        w-full flex py-2.5 px-5 justify-between">
          <Link href={HomePath()} className="text-lg font-bold">
            Home 
          </Link>
          <Link href={ticketsPath()} className="text-sm underline">
            Tickets
          </Link>
        </nav>
        <main className="
              min-h-screen flex-1
              overflow-y-auto overflow-x-hidden
              py-24 px-8
              bg-secondary/20
              flex flex-col
              ">
                {children}
        </main>
      </body>
    </html>
  );
}
